=== salaruioana/About-Me---Full-Stack-Project/continut/resurse/persoane.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:complexType name="tipAdresa">
    <xs:sequence>
      <xs:element name="strada" type="xs:string"/>
      <xs:element name="numar" type="xs:integer"/>
      <xs:element name="localitate" type="xs:string"/>
      <xs:element name="judet" type="xs:string"/>
      <xs:element name="tara" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipJob">
    <xs:sequence>
      <xs:element name="companie" type="xs:string"/>
      <xs:element name="rol" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipPersoana">
    <xs:sequence>
      <xs:element name="nume" type="xs:string"/>
      <xs:element name="prenume" type="xs:string"/>
      <xs:element name="varsta" type="xs:integer"/>
      <xs:element name="adresa" type="tipAdresa"/>
      <xs:element name="job" type="tipJob"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

  <xs:element name="persoane">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persoana" type="tipPersoana" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== salaruioana/About-Me---Full-Stack-Project/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>

<persoane xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="persoane.xsd">
    <persoana id = "1">
        <nume>Hepburn</nume>
        <prenume>Audrey</prenume>
        <varsta>63</varsta>
        <adresa>
            <strada>La Paisible</strada>
            <numar>1</numar>
            <localitate>Tolochenaz</localitate>
            <judet>Vaud</judet>
            <tara>Elveția</tara>
        </adresa>
        <job>
            <companie>UNICEF</companie>
            <rol>Goodwill Ambassador</rol>
        </job>
    </persoana>
    <persoana id = "2">
        <nume>Grant</nume>
        <prenume>Elizabeth Woolridge</prenume>
        <varsta>39</varsta>
        <adresa>
            <strada>Ocean Avenue</strada>
            <numar>45</numar>
            <localitate>Malibu</localitate>
            <judet>California</judet>
            <tara>Statele Unite ale Americii</tara>
        </adresa>
        <job>
            <companie>Interscope Records</companie>
            <rol>Cântăreță</rol>
        </job>
    </persoana>
    <persoana id = "3">
        <nume>Grande</nume>
        <prenume>Ariana</prenume>
        <varsta>31</varsta>
        <adresa>
            <strada>Boca Raton Blvd</strada>
            <numar>777</numar>
            <localitate>Boca Raton</localitate>
            <judet>Florida</judet>
            <tara>Statele Unite ale Americii</tara>
        </adresa>
        <job>
            <companie>r.e.m. beauty</companie>
            <rol>CEO</rol>
        </job>
    </persoana>
</persoane>
